### PR TITLE
Log_in Template added

### PR DESCRIPTION
**Pull request by Pabloj20**
Login page design #42

### CODE REVIEW

**Comment by Pabloj20** [comment]
login

**Review by ale1311sv — APPROVED** [review]

**Review by peillis — CHANGES_REQUESTED** [review]
As you can see below, there is a common pattern design in the login pages, which is password below email.
So, don't reinvent the wheel please.

image
image
image

**Comment by peillis** [comment]
Also, be careful because all the menus and New Invoice button shouldn't be visible for a not logged in user.

**Comment by Pabloj20** [comment]
login

**Comment by Pabloj20** [comment]
responsive button

**Review by peillis — APPROVED** [review]

**Pull request merged**
